#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom arrow write_parquet
#' @importFrom dplyr bind_cols
#' @importFrom dplyr bind_rows
#' @importFrom dplyr distinct
#' @importFrom dplyr filter
#' @importFrom dplyr group_by
#' @importFrom dplyr if_else
#' @importFrom dplyr inner_join
#' @importFrom dplyr lag
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr relocate
#' @importFrom dplyr rename
#' @importFrom dplyr select
#' @importFrom dplyr semi_join
#' @importFrom dplyr slice_head
#' @importFrom dplyr slice_sample
#' @importFrom dplyr summarize
#' @importFrom dplyr ungroup
#' @importFrom fable ARIMA
#' @importFrom fable ETS
#' @importFrom fable NNETAR
#' @importFrom fable.prophet prophet
#' @importFrom fabletools decomposition_model
#' @importFrom fabletools forecast
#' @importFrom fabletools hilo
#' @importFrom fabletools model
#' @importFrom feasts STL
#' @importFrom generics glance
#' @importFrom generics interpolate
#' @importFrom here here
#' @importFrom janitor clean_names
#' @importFrom measurements conv_unit
#' @importFrom progressr handler_progress
#' @importFrom progressr handlers
#' @importFrom progressr progressor
#' @importFrom progressr with_progress
#' @importFrom purrr map_dbl
#' @importFrom purrr map_dfr
#' @importFrom quarto quarto_render
#' @importFrom readxl read_excel
#' @importFrom tibble as_tibble
#' @importFrom tidyr fill
#' @importFrom tidyr pivot_wider
#' @importFrom tsibble as_tsibble
#' @importFrom tsibble fill_gaps
#' @importFrom tsibble group_by_key
#' @importFrom tsibble new_data
#' @importFrom tsibble yearweek
## usethis namespace: end
NULL
